### PR TITLE
21 update react

### PR DESCRIPTION
**Pull request by dkuku**
I created new project using latest create-react-app and copied the files.
Now react is updated from 16.2 to 16.6.
I also got rid completely of bootstrap 3. Now the modals on main page are generated using semantic ui, just like the rest of the project. Home page needs adjustments but this is a good start.

### CODE REVIEW

**Comment by dkuku** [comment]
It would be nice to have it merged so I don't have to edit merge conflicts every time I'm pushing my code up. I merged changes from #mattwr18/19-events-calendar branch from saturday so it should be all updated. 
```
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |     45.6 |    34.48 |    55.41 |    44.69 |                   |
 src                   |     3.39 |        0 |        0 |     3.39 |                   |
  AboutUs.js           |        0 |      100 |        0 |        0 |               1,5 |
  index.js             |        0 |      100 |      100 |        0 |... 16,17,18,19,46 |
  modals.js            |      100 |      100 |      100 |      100 |                   |
  serviceWorker.js     |        0 |        0 |        0 |        0 |... 23,130,131,132 |
  setupTests.js        |      100 |      100 |      100 |      100 |                   |
 src/actions           |    77.42 |      100 |    83.33 |    77.27 |                   |
  getEventsAction.js   |      100 |      100 |      100 |      100 |                   |
  getHangoutsAction.js |      100 |      100 |      100 |      100 |                   |
  getProjectsAction.js |    46.15 |      100 |       50 |       50 |    15,16,17,18,20 |
 src/components        |    45.95 |       40 |    59.38 |    47.14 |                   |
  DropdownMenu.js      |      100 |      100 |      100 |      100 |                   |
  EventCard.js         |        0 |      100 |        0 |        0 |       1,2,3,4,8,9 |
  EventsList.js        |        0 |        0 |        0 |        0 |... 33,37,38,63,72 |
  HangoutCard.js       |      100 |      100 |      100 |      100 |                   |
  HangoutsList.js      |    90.91 |      100 |    85.71 |      100 |                   |
  Homepage.js          |      100 |      100 |      100 |      100 |                   |
  HomepageModal.js     |      100 |      100 |      100 |      100 |                   |
  Navbar.js            |      100 |      100 |      100 |      100 |                   |
  Project.js           |      100 |      100 |      100 |      100 |                   |
  ProjectsList.js      |        0 |      100 |        0 |        0 |   1,2,3,7,8,16,21 |
  ThemingLayout.js     |        0 |      100 |        0 |        0 |           1,2,4,5 |
 src/containers        |       90 |      100 |       80 |      100 |                   |
  ProjectsList.js      |       90 |      100 |       80 |      100 |                   |
 src/fixtures          |      100 |      100 |      100 |      100 |                   |
  events.js            |      100 |      100 |      100 |      100 |                   |
  hangouts.js          |      100 |      100 |      100 |      100 |                   |
  homepageModals.js    |      100 |      100 |      100 |      100 |                   |
  projects.js          |      100 |      100 |      100 |      100 |                   |
 src/reducers          |      100 |      100 |      100 |      100 |                   |
  eventsReducer.js     |      100 |      100 |      100 |      100 |                   |
  hangoutsReducer.js   |      100 |      100 |      100 |      100 |                   |
  initialState.js      |      100 |      100 |      100 |      100 |                   |
  projectsReducer.js   |      100 |      100 |      100 |      100 |                   |
 src/store             |      100 |      100 |      100 |      100 |                   |
  index.js             |      100 |      100 |      100 |      100 |                   |
 src/types             |      100 |      100 |      100 |      100 |                   |
  index.js             |      100 |      100 |      100 |      100 |                   |
-----------------------|----------|----------|----------|----------|-------------------|
```
Also finished porting the landing page:
2018-12-10-020527_1920x1080_scrot

**Comment by Kachulio1** [comment]
99 files change wow, @FedericoEsparza when are you going to start reviewing

**Comment by FedericoEsparza** [comment]
@Kachulio1 I'll start today. Let's coordinate in the scrum.

**Comment by dkuku** [comment]
I fixed the calendar - it's not "going to nowhere" when you change the view, also I got rid of the localstorage for now - it makes development harder
2018-12-10-193316_1920x1080_scrot

**Pull request closed without merging**
